version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  simulacija:
    build:
      context: .
      dockerfile: Dockerfile_sim
    environment:
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
  test_simulator:
    build:
      context: .
      dockerfile: Dockerfile_test
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      adresa_simluacionog_servisa: "http://simulacija:5002"
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    volumes:
      - .:/app