version: '3'
services:
  simulatorAPI:
    build:
      context: .
      dockerfile: Dockerfile_sim
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  test_simulator:
    build:
      context: .
      dockerfile: Dockerfile_test
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"